global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9308']

  - job_name: 'graphql-gateway'
    static_configs:
      - targets: ['graphql-gateway:9200']

  - job_name: 'user-service'
    static_configs:
      - targets: ['users-service:9201']

  - job_name: 'product-service'
    static_configs:
      - targets: ['products-service:9202']

  - job_name: 'order-service'
    static_configs:
      - targets: ['orders-service:9203']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notifications-service:9204']

  - job_name: 'recommendation-service'
    static_configs:
      - targets: ['recommendations-service:9205']
